-- ─────────────────────────────────────────────
-- SNAPSAVE PRO — MongoDB Schema Reference
-- This file is for documentation only.
-- The actual schema is managed by MongoDB collections.
-- ─────────────────────────────────────────────

-- Legacy SQL schema removed in favor of MongoDB.
-- MongoDB collections will be set up programmatically.

-- Collection: users
-- {
--   _id: ObjectId,
--   email: String (unique),
--   password_hash: String,
--   full_name: String,
--   username: String (unique),
--   avatar_url: String,
--   country: String,
--   is_pro: Boolean (default: false),
--   download_count_ig: Number (default: 0),
--   download_count_yt: Number (default: 0),
--   last_reset_date: String (YYYY-MM-DD),
--   created_at: Date,
--   updated_at: Date
-- }
